# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSalida():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_salida(self):
    self.driver.get("https://checkio.connectis.es/checkio/gestion/fichar")
    self.driver.set_window_size(968, 528)
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-focused > .mat-button-wrapper > div > div").click()
  
